# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 506038041e58cc632cbc6d78904f7d2b590dc43e7b141bcdd2741d3ab22388c6837bbe84c2bae3e94a1d31c028b2af2e182e8c85e8620182cf87780a3144e8b7

test:
  secret_key_base: 10010ec3cece4607f110b59cc2698c89ee8950d01c95301cda0529ccec66c2db1ca4eca7c003cb5facc41288c0bc001d51a93c4008d975f9f29d2887e194f3a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
